# Generated by Django 3.2.3 on 2021-07-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20210721_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date_n_time',
            field=models.DateTimeField(default='2021-07-21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
